### ISSUE TITLE
DeadObjectException Force finishing activity

### ISSUE THREAD

**Issue by kateLee** [paypal/PayPal-Android-SDK#191]
Hello everyone,
I found some error, does anyone know how to fix that?

Asus zenfone with Android 4.3 will crash when launch PaymentActivity.
Error message like that: DeadObjectException Force finishing activity.

Thank you.

**Comment by mattjacunski** [comment]
@kateLee - We will need more information to understand what is going on here.  What version of the SDK are you running?  Please share logcat output that includes the crash.  Thanks.

**Comment by kateLee** [comment]
PayPalSDK/PayPal-Android-SDK 2.9.11 (Android 4.3; asus ASUS_T00J; )

I copy the part of logcat output, hope it can help.
```
09-03 11:32:41.355   3346-18203/? W/ActivityManager﹕ Force finishing activity com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity
09-03 11:32:41.365    166-18533/? E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 67
09-03 11:32:41.385    3346-3356/? I/WindowState﹕ WIN DEATH: Window{220d4ef0 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.example.paypalandroidsdkexample.SampleActivity}
09-03 11:32:41.395    3346-3346/? I/WindowState﹕ WIN DEATH: Window{220fb340 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity}
09-03 11:32:41.395   3346-29837/? I/WindowState﹕ WIN DEATH: Window{220f4c18 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity}
09-03 11:32:41.415   3346-18203/? D/WindowManager﹕ adjustConfigurationLw, config:{1.3 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 320dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
09-03 11:32:41.415   3346-18203/? W/ActivityManager﹕ Exception thrown during pause
    android.os.DeadObjectException
            at android.os.BinderProxy.transact(Native Method)
            at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:685)
            at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1243)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4410)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4342)
            at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9496)
            at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9284)
            at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10078)
            at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9607)
            at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
09-03 11:32:41.415   3346-18203/? W/ActivityManager﹕ Exception when starting activity com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity
    android.os.DeadObjectException
            at android.os.BinderProxy.transact(Native Method)
            at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:773)
            at com.android.server.am.ActivityStack.realStartActivityLocked(ActivityStack.java:942)
            at com.android.server.am.ActivityStack.startSpecificActivityLocked(ActivityStack.java:1054)
            at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:2095)
            at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1703)
            at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1294)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4410)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4342)
            at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9496)
            at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9284)
            at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10078)
            at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9607)
            at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
09-03 11:32:41.445   3346-18203/? E/NativeCrashListener﹕ Unable to report native crash
    java.lang.IndexOutOfBoundsException: Invalid index 9, size is 8
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9503)
            at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9284)
            at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10078)
            at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9607)
            at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by kateLee** [comment]
I think maybe it is *.so error, so I copy its output , too.

```
09-03 11:32:41.175      166-265/? E/IMGSRV﹕ :0: PVRDRMOpen: TP3, ret = 34
09-03 11:32:41.285      165-165/? I/DEBUG﹕ eax 00000000  ebx 000000c6  ecx 00000000  edx 00000000
09-03 11:32:41.285      165-165/? I/DEBUG﹕ esi 00000e59  edi 00000000
09-03 11:32:41.285      165-165/? I/DEBUG﹕ xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000043  xss 0000007b
09-03 11:32:41.295      165-165/? I/DEBUG﹕ eip 643493b5  ebp 2200ff0c  esp 2200fec4  flags 00210246
09-03 11:32:41.305      165-165/? I/DEBUG﹕ backtrace:
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #00  pc 000873b5  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #01  pc 000854ae  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #02  pc 00072568  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #03  pc 0006ecc5  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #04  pc 0006e8af  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #05  pc 000b935e  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #06  pc ffffffff  <unknown>
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #07  pc 00143bba  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #08  pc 0018b550  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #09  pc 0000001e  <unknown>
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #10  pc 00160c88  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #11  pc 00143bd5  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #12  pc 00183d37  /system/lib/libhoudini.so.3.4.6.44569
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #13  pc 0020f6cd  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #14  pc 000d7d06  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #15  pc 00217699  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #16  pc 0001cd43  <unknown>
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #17  pc 0008ccf1  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #18  pc 0010ab4e  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #19  pc 0010aea7  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #20  pc 00126ee4  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #21  pc 0012950f  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #22  pc 0007e47f  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #23  pc 003489af  /dev/ashmem/dalvik-heap (deleted)
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #24  pc 0008ccf1  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #25  pc 0010ab4e  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #26  pc 0010aea7  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #27  pc 000e8dba  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #28  pc 0001b6cc  /system/lib/libc.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #29  pc 0003da65  /system/lib/libc.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ #30  pc 000e8a0f  /system/lib/libdvm.so
09-03 11:32:41.305      165-165/? I/DEBUG﹕ stack:
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c17f0  642c1f00
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c17f4  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c17f8  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c17fc  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c1800  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c1804  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c1808  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c180c  00000000
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c1810  00000002
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c1814  00000003
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c1818  642c186c
09-03 11:32:41.305      165-165/? I/DEBUG﹕ 642c181c  642c185c
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1820  618864b0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1824  59394cf0  /dev/ashmem/dalvik-LinearAlloc (deleted)
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1828  642c18a8
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c182c  412bc6ce  /system/lib/libdvm.so
09-03 11:32:41.315      165-165/? I/DEBUG﹕ #13  642c1830  618864b0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1834  43b5f6d0  /dev/ashmem/dalvik-heap (deleted)
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1838  41322f38  /system/lib/libdvm.so
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c183c  412bc6ce  /system/lib/libdvm.so
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1840  00000000
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1844  380015f5  /data/app-lib/com.paypal.example.paypalandroidsdkexample.debug-1/libcardioDecider.so
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1848  0000005a
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c184c  618864c0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1850  00000002
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1854  642c186c
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1858  642c185c
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c185c  642c18b0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1860  642c18b4
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1864  5c947000  /dev/ashmem/dalvik-aux-structure (deleted)
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c1868  59394cf0  /dev/ashmem/dalvik-LinearAlloc (deleted)
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c186c  50004c4c  /dev/ashmem/dalvik-heap (deleted)
09-03 11:32:41.315      165-165/? I/DEBUG﹕ ........  ........
09-03 11:32:41.315      165-165/? I/DEBUG﹕ #14  642c18b0  61886dc0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18b4  1d600001
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18b8  70000001
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18bc  00000000
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18c0  61894d44
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18c4  60abee39  /data/dalvik-cache/data@app@com.paypal.example.paypalandroidsdkexample.debug-1.apk@classes.dex
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18c8  380015f5  /data/app-lib/com.paypal.example.paypalandroidsdkexample.debug-1/libcardioDecider.so
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18cc  618864c0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18d0  0000038c
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18d4  00000000
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18d8  61894d44
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18dc  618864c0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18e0  43b5f6d0  /dev/ashmem/dalvik-heap (deleted)
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18e4  1d600001
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18e8  0004a901
09-03 11:32:41.315      165-165/? I/DEBUG﹕ 642c18ec  618864c0
09-03 11:32:41.315      165-165/? I/DEBUG﹕ ........  ........
09-03 11:32:41.315      165-165/? I/DEBUG﹕ #15  642c1910  61894d44
09-03 11:32:41.315      165-165/? I/DEBUG﹕ ........  ........
```

**Comment by ppmtscory** [comment]
@kateLee were you able to get this resolved at all?  Have you attempted with the latest SDK version 2.10.1?

**Comment by kateLee** [comment]
update with the latest SDK version 2.10.1 still happened.
Like the earlier version, Asus zenfone with Android 4.3 will crash, but Asus zenfone with Android 4.4 will not. 

10-15 16:40:31.455  22425-22432/com.paypal.example.paypalandroidsdkexample.debug I/dalvikvm﹕ Total arena pages for JIT: 21
10-15 16:40:31.465  22425-22597/com.paypal.example.paypalandroidsdkexample.debug D/houdini﹕ [22597] Loading library(version: 3.4.6.44569 RELEASE)... successfully.
10-15 16:40:31.485  22425-22597/com.paypal.example.paypalandroidsdkexample.debug D/dalvikvm﹕ Added shared lib /data/app-lib/com.paypal.example.paypalandroidsdkexample.debug-1/libcardioDecider.so 0x437f22e0
10-15 16:40:31.495  22425-22597/com.paypal.example.paypalandroidsdkexample.debug A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 22597 (AsyncTask #1)
10-15 16:40:31.595      169-169/? I/DEBUG﹕ pid: 22425, tid: 22597, name: AsyncTask #1  >>> com.paypal.example.paypalandroidsdkexample.debug <<<
10-15 16:40:31.895      169-169/? I/DEBUG﹕ 63cbe844  380015f5  /data/app-lib/com.paypal.example.paypalandroidsdkexample.debug-1/libcardioDecider.so
10-15 16:40:31.895      169-169/? I/DEBUG﹕ 63cbe8c4  609bee39  /data/dalvik-cache/data@app@com.paypal.example.paypalandroidsdkexample.debug-1.apk@classes.dex
10-15 16:40:31.895      169-169/? I/DEBUG﹕ 63cbe8c8  380015f5  /data/app-lib/com.paypal.example.paypalandroidsdkexample.debug-1/libcardioDecider.so
10-15 16:40:31.935    467-22607/? W/ActivityManager﹕ Force finishing activity com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity
10-15 16:40:31.965      467-549/? W/InputDispatcher﹕ channel '21ed0ae0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.example.paypalandroidsdkexample.SampleActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-15 16:40:31.965      467-549/? E/InputDispatcher﹕ channel '21ed0ae0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.example.paypalandroidsdkexample.SampleActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-15 16:40:31.965      467-549/? W/InputDispatcher﹕ channel '21fa8898 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-15 16:40:31.965      467-549/? E/InputDispatcher﹕ channel '21fa8898 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-15 16:40:31.965      467-549/? W/InputDispatcher﹕ channel '21f661f0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-15 16:40:31.965      467-549/? E/InputDispatcher﹕ channel '21f661f0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-15 16:40:31.965     467-8944/? W/InputDispatcher﹕ Attempted to unregister already unregistered input channel '21ed0ae0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.example.paypalandroidsdkexample.SampleActivity (server)'
10-15 16:40:31.965     467-8944/? I/WindowState﹕ WIN DEATH: Window{21ed0ae0 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.example.paypalandroidsdkexample.SampleActivity}
10-15 16:40:31.975     467-4728/? W/InputDispatcher﹕ Attempted to unregister already unregistered input channel '21f661f0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity (server)'
10-15 16:40:31.975     467-4728/? I/WindowState﹕ WIN DEATH: Window{21f661f0 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity}
10-15 16:40:31.985    467-20331/? W/InputDispatcher﹕ Attempted to unregister already unregistered input channel '21fa8898 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity (server)'
10-15 16:40:31.985    467-20331/? I/WindowState﹕ WIN DEATH: Window{21fa8898 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentMethodActivity}
10-15 16:40:31.995    467-22607/? I/ActivityManager﹕ Restarting because process died: ActivityRecord{21c26e10 u0 com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity}
10-15 16:40:32.005    467-22607/? W/ActivityManager﹕ Exception when starting activity com.paypal.example.paypalandroidsdkexample.debug/com.paypal.android.sdk.payments.PaymentActivity
    android.os.DeadObjectException
            at android.os.BinderProxy.transact(Native Method)

**Comment by pp-randy** [comment]
closing due to inactivity
